site_name: Alfred Discord Bot
theme:
  name: material
  favicon: assets/bat.png
  icon:
    logo: material/bat
  features:
    - navigation.tabs
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4 
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

repo_url: https://github.com/AlfredDiscordBot/alfred-discord-bot
repo_name: AlfredDiscordBot/alfred-discord-bot

edit_uri: ''

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Learn: Learn.md
  - Contributing: contributing.md
  - Privacy Policy: Privacy_Policy.md
